version: '3.8'

services:
  iptv-web:
    image: ghcr.io/jsanderstechnologies/iptv:latest
    container_name: iptv-web
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./output:/app/iptv/output
