version: '3.8'

services:
  iptv:
    image: ghcr.io/jsanderstechnologies/iptv:latest
    container_name: iptv
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./output:/app/iptv/output
